# Generated by Django 3.0.5 on 2021-05-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('ct_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ct_name', models.CharField(max_length=100)),
                ('ct_image', models.CharField(max_length=100)),
                ('ct_weight', models.CharField(max_length=100)),
                ('ct_price', models.CharField(max_length=100)),
                ('ct_total_amount', models.IntegerField()),
                ('ct_ordered_by', models.CharField(max_length=100)),
                ('ct_status', models.CharField(max_length=100)),
                ('ct_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('or_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('or_name', models.CharField(max_length=100)),
                ('or_weight', models.CharField(max_length=100)),
                ('or_rate', models.CharField(max_length=100)),
                ('or_total_amount', models.CharField(max_length=100)),
                ('or_address', models.CharField(max_length=100)),
                ('or_ordered_by', models.CharField(max_length=100)),
                ('or_date', models.CharField(max_length=100)),
                ('or_transaction_id', models.CharField(max_length=100)),
                ('or_status', models.CharField(max_length=100)),
                ('or_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ap_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ap_image', models.ImageField(upload_to='raw_material/static/media/products/')),
                ('ap_type', models.CharField(max_length=100)),
                ('ap_name', models.CharField(max_length=100)),
                ('ap_weight', models.CharField(max_length=100)),
                ('ap_rate', models.CharField(max_length=100)),
                ('ap_description', models.CharField(max_length=100)),
                ('ap_status', models.CharField(max_length=100)),
                ('ap_created_by', models.CharField(max_length=100)),
                ('ap_created_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('rg_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('rg_name', models.CharField(max_length=100)),
                ('rg_mobile', models.CharField(max_length=100)),
                ('rg_email', models.CharField(max_length=100)),
                ('rg_password', models.CharField(max_length=100)),
                ('rg_address', models.CharField(max_length=100)),
                ('rg_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('rv_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('rv_ap_id', models.CharField(max_length=100)),
                ('rv_name', models.CharField(max_length=100)),
                ('rv_email', models.CharField(max_length=100)),
                ('rv_message', models.CharField(max_length=100)),
                ('rv_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('sh_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('sh_shipping_status', models.CharField(max_length=100)),
                ('sh_ordered_by', models.CharField(max_length=100)),
                ('sh_status', models.CharField(max_length=100)),
                ('sh_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vd_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('vd_name', models.CharField(max_length=100)),
                ('vd_mobile', models.CharField(max_length=100)),
                ('vd_email', models.CharField(max_length=100)),
                ('vd_address', models.CharField(max_length=100)),
                ('vd_status', models.CharField(max_length=100)),
                ('vd_created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
