# Generated by Django 4.0.4 on 2022-06-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0002_cart_order_product_register_review_shipping_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='or_time',
            field=models.CharField(default='', max_length=100),
        ),
    ]
